# Generated by Django 3.1.6 on 2021-02-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='picture',
        ),
    ]
