# Generated by Django 3.1.6 on 2021-02-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210202_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='picture',
            new_name='main_image',
        ),
    ]
