# Generated by Django 3.1.6 on 2021-02-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20210202_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='projects/%Y/%m/%d'),
        ),
    ]
