# Generated by Django 3.1.6 on 2021-02-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20210205_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='staff/%Y/%m/%d')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('introduction', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='section_text',
            field=models.TextField(blank=True),
        ),
    ]
