# Generated by Django 3.1.6 on 2021-02-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20210208_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='section_text',
        ),
    ]
